/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "calcute_server_constants.h"



const calcute_serverConstants g_calcute_server_constants;

calcute_serverConstants::calcute_serverConstants() {
}



