/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef calcute_server_CONSTANTS_H
#define calcute_server_CONSTANTS_H

#include "calcute_server_types.h"



class calcute_serverConstants {
 public:
  calcute_serverConstants();

};

extern const calcute_serverConstants g_calcute_server_constants;



#endif
