/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "deal_message_constants.h"



const deal_messageConstants g_deal_message_constants;

deal_messageConstants::deal_messageConstants() {
}



