/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "ip_rule_constants.h"



const ip_ruleConstants g_ip_rule_constants;

ip_ruleConstants::ip_ruleConstants() {
}



