/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef ip_rule_CONSTANTS_H
#define ip_rule_CONSTANTS_H

#include "ip_rule_types.h"



class ip_ruleConstants {
 public:
  ip_ruleConstants();

};

extern const ip_ruleConstants g_ip_rule_constants;



#endif
