/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef deal_message_CONSTANTS_H
#define deal_message_CONSTANTS_H

#include "deal_message_types.h"



class deal_messageConstants {
 public:
  deal_messageConstants();

};

extern const deal_messageConstants g_deal_message_constants;



#endif
