// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "RecvMessage.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

using namespace  ;

class RecvMessageHandler : virtual public RecvMessageIf {
 public:
  RecvMessageHandler() {
    // Your initialization goes here
  }

  void registe_group(const Group& grp) {
    // Your implementation goes here
    printf("registe_group\n");
  }

  void registe_device(const Device& dev) {
    // Your implementation goes here
    printf("registe_device\n");
  }

  void send_measure_info(const std::string& msg) {
    // Your implementation goes here
    printf("send_measure_info\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  shared_ptr<RecvMessageHandler> handler(new RecvMessageHandler());
  shared_ptr<TProcessor> processor(new RecvMessageProcessor(handler));
  shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

